//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWallet.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyWallet.Client.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account name.
        /// </summary>
        internal static string AccountName {
            get {
                return ResourceManager.GetString("AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage accounts, change icons, color and description.
        /// </summary>
        internal static string AccountsDescription {
            get {
                return ResourceManager.GetString("AccountsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts settings.
        /// </summary>
        internal static string AccountsSettings {
            get {
                return ResourceManager.GetString("AccountsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more cards.
        /// </summary>
        internal static string AddMoreCards {
            get {
                return ResourceManager.GetString("AddMoreCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust balance.
        /// </summary>
        internal static string AdjustBalance {
            get {
                return ResourceManager.GetString("AdjustBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All categories.
        /// </summary>
        internal static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? .
        /// </summary>
        internal static string AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account number.
        /// </summary>
        internal static string BankAccountNumber {
            get {
                return ResourceManager.GetString("BankAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets.
        /// </summary>
        internal static string Budgets {
            get {
                return ResourceManager.GetString("Budgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card configuration.
        /// </summary>
        internal static string CardConfiguration {
            get {
                return ResourceManager.GetString("CardConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash flow.
        /// </summary>
        internal static string CashFlow {
            get {
                return ResourceManager.GetString("CashFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage categories, change icons, color and description.
        /// </summary>
        internal static string CategoriesDescription {
            get {
                return ResourceManager.GetString("CategoriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category nature.
        /// </summary>
        internal static string CategoryNature {
            get {
                return ResourceManager.GetString("CategoryNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a color.
        /// </summary>
        internal static string ChooseAColor {
            get {
                return ResourceManager.GetString("ChooseAColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an account currency.
        /// </summary>
        internal static string ChooseAnAccountCurrency {
            get {
                return ResourceManager.GetString("ChooseAnAccountCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an account type.
        /// </summary>
        internal static string ChooseAnAccountType {
            get {
                return ResourceManager.GetString("ChooseAnAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Facebook.
        /// </summary>
        internal static string ConnectWithFacebook {
            get {
                return ResourceManager.GetString("ConnectWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Google.
        /// </summary>
        internal static string ConnectWithGoogle {
            get {
                return ResourceManager.GetString("ConnectWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create account.
        /// </summary>
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        internal static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add other currencies, adjust exchange rates.
        /// </summary>
        internal static string CurrenciesDescription {
            get {
                return ResourceManager.GetString("CurrenciesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency rates.
        /// </summary>
        internal static string CurrencyRates {
            get {
                return ResourceManager.GetString("CurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 days.
        /// </summary>
        internal static string Days30 {
            get {
                return ResourceManager.GetString("Days30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 days.
        /// </summary>
        internal static string Days7 {
            get {
                return ResourceManager.GetString("Days7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        internal static string Debts {
            get {
                return ResourceManager.GetString("Debts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all user data.
        /// </summary>
        internal static string DeleteAllUserData {
            get {
                return ResourceManager.GetString("DeleteAllUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete temporary data.
        /// </summary>
        internal static string DeleteTempData {
            get {
                return ResourceManager.GetString("DeleteTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string DontHaveAnAccount {
            get {
                return ResourceManager.GetString("DontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit account.
        /// </summary>
        internal static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        internal static string EditCategory {
            get {
                return ResourceManager.GetString("EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit currency.
        /// </summary>
        internal static string EditCurrency {
            get {
                return ResourceManager.GetString("EditCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email....
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password....
        /// </summary>
        internal static string EnterConfirmPasswordDots {
            get {
                return ResourceManager.GetString("EnterConfirmPasswordDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email....
        /// </summary>
        internal static string EnterEmailDots {
            get {
                return ResourceManager.GetString("EnterEmailDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter first name....
        /// </summary>
        internal static string EnterFirstNameDots {
            get {
                return ResourceManager.GetString("EnterFirstNameDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter last name....
        /// </summary>
        internal static string EnterLastNameDots {
            get {
                return ResourceManager.GetString("EnterLastNameDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name....
        /// </summary>
        internal static string EnterNameDots {
            get {
                return ResourceManager.GetString("EnterNameDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number....
        /// </summary>
        internal static string EnterNumberDots {
            get {
                return ResourceManager.GetString("EnterNumberDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password....
        /// </summary>
        internal static string EnterPasswordDots {
            get {
                return ResourceManager.GetString("EnterPasswordDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By signing up or connecting with the services above you agree to our .
        /// </summary>
        internal static string EntryPageTextPart1 {
            get {
                return ResourceManager.GetString("EntryPageTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and acknowledge our .
        /// </summary>
        internal static string EntryPageTextPart2 {
            get {
                return ResourceManager.GetString("EntryPageTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  describing how we handle your personal data..
        /// </summary>
        internal static string EntryPageTextPart3 {
            get {
                return ResourceManager.GetString("EntryPageTextPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. If the problem persists, please contact support via email.
        /// </summary>
        internal static string ErrorMessagePart1 {
            get {
                return ResourceManager.GetString("ErrorMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with an error message:.
        /// </summary>
        internal static string ErrorMessagePart2 {
            get {
                return ResourceManager.GetString("ErrorMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-Oh!.
        /// </summary>
        internal static string ErrorMessageTitle {
            get {
                return ResourceManager.GetString("ErrorMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude from stats.
        /// </summary>
        internal static string ExcludeFromStats {
            get {
                return ResourceManager.GetString("ExcludeFromStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        internal static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group sharing.
        /// </summary>
        internal static string GroupSharing {
            get {
                return ResourceManager.GetString("GroupSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In developing....
        /// </summary>
        internal static string InDeveloping {
            get {
                return ResourceManager.GetString("InDeveloping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial value.
        /// </summary>
        internal static string InitialValue {
            get {
                return ResourceManager.GetString("InitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverse rate.
        /// </summary>
        internal static string InverseRate {
            get {
                return ResourceManager.GetString("InverseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite friends.
        /// </summary>
        internal static string InviteFriends {
            get {
                return ResourceManager.GetString("InviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 12 weeks.
        /// </summary>
        internal static string Last12Weeks {
            get {
                return ResourceManager.GetString("Last12Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 1 year.
        /// </summary>
        internal static string Last1Year {
            get {
                return ResourceManager.GetString("Last1Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 30 days.
        /// </summary>
        internal static string Last30Days {
            get {
                return ResourceManager.GetString("Last30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 5 years.
        /// </summary>
        internal static string Last5Years {
            get {
                return ResourceManager.GetString("Last5Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 6 month.
        /// </summary>
        internal static string Last6Month {
            get {
                return ResourceManager.GetString("Last6Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 7 days.
        /// </summary>
        internal static string Last7Days {
            get {
                return ResourceManager.GetString("Last7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last records overview.
        /// </summary>
        internal static string LastRecordsOverview {
            get {
                return ResourceManager.GetString("LastRecordsOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of accounts.
        /// </summary>
        internal static string ListOfAccounts {
            get {
                return ResourceManager.GetString("ListOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty cards.
        /// </summary>
        internal static string LoyaltyCards {
            get {
                return ResourceManager.GetString("LoyaltyCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 month.
        /// </summary>
        internal static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New account.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New currency.
        /// </summary>
        internal static string NewCurrency {
            get {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a nice day!.
        /// </summary>
        internal static string NiceDay {
            get {
                return ResourceManager.GetString("NiceDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any notifications..
        /// </summary>
        internal static string NoAnyNotifications {
            get {
                return ResourceManager.GetString("NoAnyNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No currency selected.
        /// </summary>
        internal static string NoCurrencySelected {
            get {
                return ResourceManager.GetString("NoCurrencySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow or no internet connection..
        /// </summary>
        internal static string NoInternetMessagePart1 {
            get {
                return ResourceManager.GetString("NoInternetMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check you internet connection and try again..
        /// </summary>
        internal static string NoInternetMessagePart2 {
            get {
                return ResourceManager.GetString("NoInternetMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        internal static string NotSpecified {
            get {
                return ResourceManager.GetString("NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        internal static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave password empty, when you don&apos;t want change it..
        /// </summary>
        internal static string PasswordChangeDescription {
            get {
                return ResourceManager.GetString("PasswordChangeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed successfully!.
        /// </summary>
        internal static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        internal static string PasswordConfirmation {
            get {
                return ResourceManager.GetString("PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min. 6 characters.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned payments.
        /// </summary>
        internal static string PlannedPayments {
            get {
                return ResourceManager.GetString("PlannedPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string Records {
            get {
                return ResourceManager.GetString("Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        internal static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select gender.
        /// </summary>
        internal static string SelectGender {
            get {
                return ResourceManager.GetString("SelectGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select period.
        /// </summary>
        internal static string SelectPeriod {
            get {
                return ResourceManager.GetString("SelectPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping lists.
        /// </summary>
        internal static string ShoppingLists {
            get {
                return ResourceManager.GetString("ShoppingLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up below to create a secure account..
        /// </summary>
        internal static string SignUpMessage {
            get {
                return ResourceManager.GetString("SignUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up using Mail.
        /// </summary>
        internal static string SignUpUsingMail {
            get {
                return ResourceManager.GetString("SignUpUsingMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start now.
        /// </summary>
        internal static string StartNow {
            get {
                return ResourceManager.GetString("StartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the big pictuer on all your money. Connect your bank, track cash, or import data. .
        /// </summary>
        internal static string StartScreen1Description {
            get {
                return ResourceManager.GetString("StartScreen1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Finances in One Place.
        /// </summary>
        internal static string StartScreen1Title {
            get {
                return ResourceManager.GetString("StartScreen1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect all your accounts from any bank. Add savings, credit cards, PayPal and more..
        /// </summary>
        internal static string StartScreen2Description {
            get {
                return ResourceManager.GetString("StartScreen2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect your Bank.
        /// </summary>
        internal static string StartScreen2Title {
            get {
                return ResourceManager.GetString("StartScreen2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track and analyse spending immediatly and automatically through our bank connection..
        /// </summary>
        internal static string StartScreen3Description {
            get {
                return ResourceManager.GetString("StartScreen3Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your Spending.
        /// </summary>
        internal static string StartScreen3Title {
            get {
                return ResourceManager.GetString("StartScreen3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track and follow what matters to you. Save for important things..
        /// </summary>
        internal static string StartScreen4Description {
            get {
                return ResourceManager.GetString("StartScreen4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up your Goals.
        /// </summary>
        internal static string StartScreen4Title {
            get {
                return ResourceManager.GetString("StartScreen4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build healthy financial habits. Control unnecessary expenses..
        /// </summary>
        internal static string StartScreen5Description {
            get {
                return ResourceManager.GetString("StartScreen5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget your money.
        /// </summary>
        internal static string StartScreen5Title {
            get {
                return ResourceManager.GetString("StartScreen5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your financial life. Make the right financial decisions. See only what is important for you..
        /// </summary>
        internal static string StartScreen6Description {
            get {
                return ResourceManager.GetString("StartScreen6Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow your plan and dreams.
        /// </summary>
        internal static string StartScreen6Title {
            get {
                return ResourceManager.GetString("StartScreen6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategories.
        /// </summary>
        internal static string Subcategories {
            get {
                return ResourceManager.GetString("Subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Services.
        /// </summary>
        internal static string TermsOfServices {
            get {
                return ResourceManager.GetString("TermsOfServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        internal static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        internal static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User devices.
        /// </summary>
        internal static string UserDevices {
            get {
                return ResourceManager.GetString("UserDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View devices you&apos;re signed in to and manage.
        /// </summary>
        internal static string UserDevicesDescription {
            get {
                return ResourceManager.GetString("UserDevicesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        internal static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile changed successfully!.
        /// </summary>
        internal static string UserProfileChangedSuccess {
            get {
                return ResourceManager.GetString("UserProfileChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change profile image, name or password, logout or delete data.
        /// </summary>
        internal static string UserProfileDescription {
            get {
                return ResourceManager.GetString("UserProfileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warranties.
        /// </summary>
        internal static string Warranties {
            get {
                return ResourceManager.GetString("Warranties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12 week.
        /// </summary>
        internal static string Week12 {
            get {
                return ResourceManager.GetString("Week12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back!.
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        internal static string Year1 {
            get {
                return ResourceManager.GetString("Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 years.
        /// </summary>
        internal static string Year5 {
            get {
                return ResourceManager.GetString("Year5", resourceCulture);
            }
        }
    }
}
